### ISSUE TITLE
Website Enhancement

### ISSUE THREAD

**Issue by yashksaini-coder** [AmateursLeague/sneaky-package#205]
Redesign the logo for the Main docs for sneaky package

@this-is-yaash kindlt assign me this issue

**Comment by this-is-yaash** [comment]
![image](https://github.com/user-attachments/assets/f425ea9c-357c-4faa-b878-747b896c5ef8)

Can you you replace this with an actual emoji icon rather than the "outline" type icon.
![image](https://github.com/user-attachments/assets/cb5888e9-939d-49e6-88ff-6df96289f355)
find a package that is similar to this and update it 
(i like this kind of icon, so try to find replacement that is similar to the img I pasted above)
